version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: new_db
    volumes:
      - ./mysql_data_new:/var/lib/mysql
    networks:
      - two-tier
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    restart: always

  flask-app:
    build:
      context: .
    container_name: flask-app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: new_db
    networks:
      - two-tier
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

volumes:
  mysql_data_new:

networks:
  two-tier:

